[package]
name = "stream_dream"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["fs", "macros", "rt-multi-thread", "io-util"] }
warp = "0.3"
